// auth related
export const CREATED_ACCOUNT = "CREATED_ACCOUNT";

export const FETCHED_USER_PROFILE = "FETCHED_USER_PROFILE";
export const SIGNED_UP = "SIGNED_UP";
export const SIGNED_IN = "SIGNED_IN";
export const SIGNED_OUT = "SIGNED_OUT";
export const FETCHED_ACCOUNT_PROFILE = "FETCHED_ACCOUNT_PROFILE";
export const UPDATED_ACCOUNT_PROFILE = "UPDATED_ACCOUNT_PROFILE";
export const FOUND_ERROR_DURING_SIGN_UP = "FOUND_ERROR_DURING_SIGN_UP";
export const FOUND_ERROR_DURING_LOGIN = "FOUND_ERROR_DURING_LOGIN";
export const ATTEMPTED_LOGIN = "ATTEMPTED_LOGIN";
export const ATTEMPTED_SIGN_UP = "ATTEMPTED_SIGN_UP";

// comments related
export const FETCHED_COMMENTS = "FETCHED_COMMENTS";

// proposals related
export const ADDED_TO_SELECTED_AUTHORS = "ADDED_TO_SELECTED_AUTHORS";
export const CHANGED_VIEW = "CHANGED_VIEW";
export const FETCHED_PROJECT_PROPOSALS = "FETCHED_PROJECT_PROPOSALS";
export const GET_PROJECT_PROPOSAL = "GET_PROJECT_PROPOSAL";
export const SHOW_PROPOSAL = "SHOW_PROPOSAL";
export const SUBMITTED_PROPOSAL = "SUBMITTED_PROPOSAL";
export const REMOVED_FROM_SELECTED_AUTHORS = "REMOVED_FROM_SELECTED_AUTHORS";
export const CHANGED_STATUS = "CHANGED_STATUS";
export const FETCHED_PROPOSAL_ADMIN_PERMISSION =
	"FETCHED_PROPOSAL_ADMIN_PERMISSION";
export const FETCHED_PROPOSAL_ACTIVITIES = "FETCHED_PROPOSAL_ACTIVITIES";
export const UNMOUNTED_PROPOSAL_DATA = "UNMOUNTED_PROPOSAL_DATA";
export const FILTERED_PROPOSAL = "FILTERED_PROPOSAL";
export const SET_SEARCH_VAL = "SET_SEARCH_VAL";
// account management
export const FETCHED_USERS = "FETCHED_USERS";

// sysTables

export const DELETED_UNVERIFIED_USERS = "DELETED_UNVERIFIED_USERS";
export const AUTH_LOADING = "AUTH_LOADING";
export const CREATED_NEW_USER = "CREATED_NEW_USER";
export const SYSTEM_SETUP_COMPLETE = "SYSTEM_SETUP_COMPLETE";

// for development purposes
export const TOGGLED_TEST_MODE = "TOGGLED_TEST_MODE";
export const TOGGLED_DEBUG_MODE = "TOGGLED_DEBUG_MODE";

export const AUTH = {
	MESSAGES: {
		SENT_EMAIL_VERIFICATION: "SENT_EMAIL_VERIFICATION",
	},
	ERRORS: {
		RECEIVED_RESET_PASSWORD_LINK_ERROR: "RECEIVED_RESET_PASSWORD_LINK_ERROR",
		RECEIVED_LOGIN_ERROR: "RECEIVED_LOGIN_ERROR",
	},
	FETCHED_AUTH_ACCOUNT_PROFILE: "FETCHED_AUTH_ACCOUNT_PROFILE",
	FETCHED_NOTIFICATIONS: "FETCHED_NOTIFICATIONS",
};
export const ACCOUNT_MANAGEMENT = {
	LOADING_ACCOUNT_SETUP: "LOADING_ACCOUNT_SETUP",
	UPDATING_ACCOUNT_PROFILE: "UPDATING_ACCOUNT_PROFILE",
	FETCHED_USER_ROLES: "FETCHED_USER_ROLES",
};

export const LOADING = {
	SYSTEM: "SYSTEM_LOADING",
};

export const SYSTEM = {
	FETCHED_SYSTEM_META_DATA: "FETCHED_SYSTEM_META_DATA",
	FETCHED_SYSTEM_DATA: "FETCHED_SYSTEM_DATA",
	FETCHED_BRANCHES_DATA: "FETCHED_BRANCHES_DATA",
	FETCHED_DEPARMENTS_DATA: "FETCHED_DEPARMENTS_DATA",
	FETCHED_ROLES_DATA: "FETCHED_ROLES_DATA",
	FETCHED_USERS_DATA: "FETCHED_USERS_DATA",
	HOOKED_SYSTEM_LISTENER: "HOOKED_SYSTEM_LISTENER",

	MESSAGES: {
		ACTIVATED_SYSTEM_SUCCESSFULLY: "ACTIVATED_SYSTEM_SUCCESSFULLY",
	},
	LOADING: {
		LOADING_SYSTEM_ACTIVATION: "LOADING_SYSTEM_ACTIVATION",
	},
	ERRORS: {
		RECEIVED_SYSTEM_ACTIVATION_ERROR: "RECEIVED_SYSTEM_ACTIVATION_ERROR",
	},
	PROPOSAL_FAQ: {
		FETCHED_PROPOSAL_FAQ_SUCCESS: "FETCHED_PROPOSAL_FAQ_SUCCESS",
		CREATED_PROPOSAL_FAQ_SUCCESS: "CREATED_PROPOSAL_FAQ_SUCCESS",
		UPDATED_PROPOSAL_FAQ_SUCCESS: "UPDATED_PROPOSAL_FAQ_SUCCESS",
		DELETED_PROPOSAL_FAQ_SUCCESS: "DELETED_PROPOSAL_FAQ_SUCCESS"
	},
	SCHOLARSHIP_FAQ: {
		FETCHED_SCHOLARSHIP_FAQ_SUCCESS: "FETCHED_SCHOLARSHIP_FAQ_SUCCESS",
		CREATED_SCHOLARSHIP_FAQ_SUCCESS: "CREATED_SCHOLARSHIP_FAQ_SUCCESS",
		UPDATED_SCHOLARSHIP_FAQ_SUCCESS: "UPDATED_SCHOLARSHIP_FAQ_SUCCESS",
		DELETED_SCHOLARSHIP_FAQ_SUCCESS: "DELETED_SCHOLARSHIP_FAQ_SUCCESS"
	}
};

export const NAV = {
	SEARCH: {
		UPDATED_SEARCH_RESULTS: "UPDATED_SEARCH_RESULTS",
		UPDATED_SEARCH_INDEX: "UPDATED_SEARCH_INDEX",
	},
	INITIATED_LEFT_NAV: "INITIATED_LEFT_NAV",
};

export const PROPOSAL = {
	FETCHED_PROJECT_PROPOSALS: "FETCHED_PROJECT_PROPOSALS",
	FETCHED_PROJECT_PROPOSAL: "FETCHED_PROJECT_PROPOSAL",
	FETCHED_PROPOSAL_COMMENTS: "FETCHED_PROPOSAL_COMMENTS",
	FETCHED_PROPOSAL_ACTIVITIES: "FETCHED_PROPOSAL_ACTIVITIES",
};
